# Generated by Django 4.2.16 on 2025-01-30 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0025_recipe_seasons'),
        ('menu', '0011_auto_20220514_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='ext_source',
            field=models.CharField(blank=True, max_length=200, verbose_name='source'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='ext_title',
            field=models.CharField(blank=True, max_length=250, verbose_name='External recipe Title'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='recipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_recipe', to='recipe.recipe'),
        ),
    ]
