# Generated by Django 2.2.28 on 2022-05-14 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0002_django_data_migration_recipe_to_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={},
        ),
    ]
