# Generated by Django 2.1.7 on 2022-05-12 17:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0003_remove_model_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rating',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
