# Generated by Django 2.2.28 on 2022-05-20 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0004_add_rating_timestamps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
