# Generated by Django 3.2.16 on 2023-04-07 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0005_rating_timestamp_remove_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='comment',
            field=models.CharField(max_length=1000, verbose_name='comment'),
        ),
    ]
