# Generated by Django 3.2.19 on 2023-05-05 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rating', '0006_alter_rating_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='update_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='rating_update', to=settings.AUTH_USER_MODEL),
        ),
    ]
