# Generated by Django 4.1.9 on 2024-01-25 07:46

from django.db import migrations, models
import django.db.models.deletion

from v1.rating.models import update_recipe_rating


def migrate_rating(apps, schema_editor):
    Recipe = apps.get_model('recipe', 'Recipe')
    for recipe in Recipe.objects.all():
        update_recipe_rating(recipe)


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0024_recipe_rating_recipe_rating_count'),
        ('rating', '0007_rating_update_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_recipe', to='recipe.recipe'),
        ),
        migrations.RunPython(migrate_rating),
    ]
