# Generated by Django 2.2.28 on 2022-05-14 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0019_auto_20220512_1305'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={},
        ),
    ]
