# Generated by Django 2.2.28 on 2022-05-22 11:28

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0020_migrate_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='photo',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='upload/recipe_photos', verbose_name='photo'),
        ),
    ]
