# Generated by Django 3.2.16 on 2022-11-04 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_groups', '0004_auto_20220514_1110'),
        ('recipe', '0021_photo_auto_resize'),
    ]

    def update_optionals(apps, schema_editor):
        Recipe = apps.get_model('recipe', 'Recipe')
        for i in Recipe.objects.all():
            if i.cook_time == -313373:
                i.cook_time = None
            if i.course and i.course.title == '-':
                i.course = None
            if i.cuisine and i.cuisine.title == '-':
                i.cuisine = None
            if i.directions and i.directions.length == 1:
                i.directions = ''
            if i.prep_time == -313373:
                i.prep_time = None
            i.save()

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cook_time',
            field=models.IntegerField(null=True, blank=True, help_text='enter time in minutes', verbose_name='cook time'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='course',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, to='recipe_groups.course'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cuisine',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, to='recipe_groups.cuisine'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='prep_time',
            field=models.IntegerField(null=True, blank=True, help_text='enter time in minutes', verbose_name='prep time'),
        ),
        migrations.RunPython(update_optionals),
    ]
