# Generated by Django 3.2.19 on 2023-05-06 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipe', '0022_migrate_required_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='update_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='recipe_update', to=settings.AUTH_USER_MODEL),
        ),
    ]
