# Generated by Django 4.2.16 on 2024-11-14 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_groups', '0005_season'),
        ('recipe', '0024_recipe_rating_recipe_rating_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recipe_groups.season'),
        ),
    ]
