# Generated by Django 2.2.28 on 2022-05-14 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_groups', '0003_auto_20180129_1456'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={},
        ),
        migrations.AlterModelOptions(
            name='cuisine',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={},
        ),
    ]
