# Generated by Django 2.1.7 on 2022-02-16 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0009_ordered_grocery_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryitem',
            name='order',
            field=models.IntegerField(default=0, verbose_name='order'),
        ),
    ]
