# Generated by Django 2.2.28 on 2022-05-14 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0010_auto_20220216_0203'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groceryitem',
            options={},
        ),
        migrations.AlterModelOptions(
            name='grocerylist',
            options={},
        ),
    ]
